[workspace]
authors = ["Joshua Sarasin <sarasinjj17@gmail.com>"]
channels = ["conda-forge"]
name = "kaggle-titanic"
platforms = ["osx-arm64","linux-64"]
version = "0.1.0"

[tasks]
download-data = "mkdir -p data/raw data/processed && kaggle competitions download -c titanic -p data/raw && unzip -o data/raw/titanic.zip -d data/raw"

[dependencies]
python = ">=3.14.0,<3.15"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.2,<2"
jupyter = ">=1.1.1,<2"
kaggle = ">=1.8.2,<2"

[activation]
scripts = [".pixi/load_dotenv.sh"]
